shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver

nodeLinker: hoisted

autoInstallPeers: false

packages:
  - app/*
  - packages/*
  - plugins/*

onlyBuiltDependencies:
  - esbuild

